### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by sofiia-tesliuk** [poc-team/Parallel_Library_of_Genetic_Algorithms#6]
ToDo list of our project:

- [x] **Library**
    - [x] Replace int -> double
    - [x] Parallelization
    - [ ] Another way to choose ancestors
    - [ ] Another way of replacement
- [x] **Visualization**
    - [x] Visualization of iteration (c++)
    - [x] Gif ~~(c++)~~ _still with python, as I haven't found normal c++ library for creating .gif_

 - - - - - 
- [x] Presentation file
- [x] Prepare performance of presentation 
- [x] **Presentation**
